language: common-lisp
sudo: required

# install ros
install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

# test with fiveam
script:
  # ultralisp is needed to ensure we're using the latest versions of other libraries
  - ros -e "(ql-dist:install-dist \"http://dist.ultralisp.org/\" :prompt nil)
            (ql:quickload :cl-patterns/tests)
            (uiop:quit (if (fiveam:run! 'cl-patterns/tests::cl-patterns-tests)
                           0 1))"

# matrix notifications on failures
notifications:
  email: false
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGRlZmF1bHR4ciUzQXN0cnVjdC53cy8lMjFNT1JMTkN0YWdLUW1jdXBvZ28lM0FzdHJ1Y3Qud3M"
    on_success: change # always|never|change
    on_failure: always
    on_start: never
