#+TITLE: cl-patterns

A library for conveniently writing patterns to generate or process sequences of mathematically(?) (un)related (compound) values in Lisp. Heavily inspired by SuperCollider's patterns system, with aims to emulate most of it, but more robust, expressive, consistent, reflective, and lispy.

- robust - strongly prefer coercing values into something "correct" rather than failing or giving an error.
- expressive - make writing music as easy and "natural" as possible, so that patterns can be built in real-time, in performance settings, without having to think so hard about how to bend the library to your will. i feel this is a weakness of SuperCollider.
- consistent - edge cases minimized, arguments for the various functions in an intuitive order. pretty self-explanatory.
- reflective - store more data about the stream state and more metadata about the patterns. make it easier for a pattern to access the values of another pattern, for patterns to affect other patterns, etc.
- lispy - prefer lisp idioms rather than direct translations of the SuperCollider way of doing things (while still keeping things relatively similar so it's not a huge adjustment for SC users to make).

In addition to emulating most of SuperCollider's patterns system, another goal is to further extend it with more tools and more ways to write patterns/sequences, for example "drum sequence" notation like ~k - - - k - - - k - - - k - - -~ for a four-to-the-floor beat. The idea is that Lisp's macros should make it possible to more expressively write music with code.

* Intro

Download cl-patterns and put it in your quicklisp ~local-projects~ directory, then load it:

#+BEGIN_SRC lisp
  (ql:quickload :cl-patterns)
  (in-package :cl-patterns)
#+END_SRC

Create a pattern like so:

#+BEGIN_SRC lisp
  (defparameter pat (pbind :foo (pseq '(1 2 3))
                           :bar (prand '(9 8 7) 5)))
#+END_SRC

Since patterns are basically "templates", you need to turn them into ~pstream~ objects in order to actually get output from them:

#+BEGIN_SRC lisp
  (defparameter pstream (as-pstream pat))
#+END_SRC

Then, you can get results from the pstream one at a time with ~next~, or many at a time with ~next-n~:

#+BEGIN_SRC lisp
  (defparameter results (next-n pstream 3))
  results
  ;; => ((EVENT :FOO 1 :BAR 8) (EVENT :FOO 2 :BAR 9) (EVENT :FOO 3 :BAR 8))
#+END_SRC

To actually play events (and hear sound output), you'll need to start an audio server. Right now, SuperCollider is the main audio server that cl-patterns is tested against, but there is also preliminary support for [[http://incudine.sourceforge.net/][Incudine]] and for MIDI output through ALSA.

In order to be able to connect to SuperCollider, you need the [[https://github.com/byulparan/cl-collider][cl-collider]] and [[http://github.com/byulparan/scheduler][scheduler]] libraries installed in your quicklisp ~local-projects~ directory so that they can be loaded. Then:

#+BEGIN_SRC lisp
  (ql:quickload :cl-patterns/supercollider)
  ;; code to start scsynth and define few example synths:
  (load #P"/path/to/cl-patterns/doc/supercollider-example.lisp")
#+END_SRC

And finally we can play patterns and hear sound:

#+BEGIN_SRC lisp
  (play (pbind :instrument :kik :freq (pseq '(100 200 400 800) 1)))
#+END_SRC

From here, you can take a look at the code in the [[file:doc/supercollider-example.lisp][doc/supercollider-example.lisp]] file for a short example of how to define your own synths. You may also be interested in [[https://defaultxr.github.io/cl-collider-tutorial/][my cl-collider tutorial]] for a more in-depth introduction to cl-collider.

For more information on how to use cl-patterns, refer to [[file:doc/tutorial.org][tutorial.org]] for an introduction.

* Features

This library isn't just a copy of SuperCollider's patterns - I wanted to improve upon them as well. For a list of notable features in cl-patterns, see [[file:doc/features.org][features.org]].

If you're familiar with SuperCollider, you may also want to look at [[file:doc/sc-differences.org][sc-differences.org]] for a listing of differences between this library and SC's patterns, or [[file:doc/sc.org][sc.org]] for a listing of patterns in SuperCollider and their equivalent (and implementation status) in cl-patterns.

* Current Status

Right now, the library may be described as being in a "alpha" state, as major changes (which may break code you write) are still very likely to happen. However, these changes should be documented in commit messages, so check those if you have any issues after updating.

However, lots of functionality is already written and the library should be stable enough for normal usage in most cases.

Many [[file:src/tests.lisp][tests]] have already been written to help guard against regressions.

Much documentation is still being written, but there is already a good amount of information in the [[file:doc/][doc]] directory, and in the docstrings for the patterns, functions, etc.

The SuperCollider backend has most functionality complete and should be usable for most purposes.

The MIDI backend has some functionality complete and should be usable for basic tasks, but is still very much a work in progress.

The Incudine backend is a stub and has very limited (if any) functionality.

See [[file:doc/TODO.org][TODO.org]] and [[file:doc/roadmap.org][roadmap.org]] for a listing of tasks that need to be completed and ideas for future features. The code itself is also littered with comments marked "FIX" noting various known issues and possible changes and optimizations that could be made.

* Tour

- [[file:README.md][README.md]] - this file. self-expanatory, i'd hope.
- [[file:package.lisp][package.lisp]] - the package definition file.
- [[file:LICENSE][LICENSE]] - the GPLv3 license.
- [[file:cl-patterns.asd][cl-patterns.asd]] - cl-patterns systems definition file.

** docs

- [[file:doc/event-special-keys.org][event-special-keys.org]] - description of keys that have special effects when used in an event or pbind.
- [[file:doc/features.org][features.org]] - listing of notable features of cl-patterns.
- [[file:doc/other-libraries.org][other-libraries.org]] - listing of other libraries that have similar goals or would be useful in conjunction with cl-patterns.
- [[file:doc/roadmap.org][roadmap.org]] - general overview of major goals for the future development of cl-patterns.
- [[file:doc/sc-differences.org][sc-differences.org]] - comprehensive description of things that differ between cl-patterns and SuperCollider.
- [[file:doc/sc.org][sc.org]] - a list of pattern classes in SuperCollider and their cl-patterns implementation status.
- [[file:doc/TODO.org][TODO.org]] - a list of things and ideas that have not yet been implemented into cl-patterns, but may be in the future.
- [[file:doc/tutorial.org][tutorial.org]] - explanation of the basic concepts of cl-patterns, meant for people who have never used SuperCollider's patterns.
- [[file:doc/supercollider-example.lisp][supercollider-example.lisp]] - short example of how to use cl-patterns with cl-collider.
- [[file:doc/writing-your-own.org][writing-your-own.org]] - information about how to write your own pattern classes.

** src

- [[file:src/utility.lisp][utility.lisp]] - general utility functions.
- [[file:src/patterns.lisp][patterns.lisp]] - the patterns themselves. includes the ~pattern~ superclass as well as ~pbind~ and ~pseq~, ~pk~, etc.
- [[file:src/event.lisp][event.lisp]] - code to represent and deal with events. includes the ~event~ class, information about special keys (i.e. ~freq~, ~amp~...), etc.
- [[file:src/clock.lisp][clock.lisp]] - the scheduling functionality to make sure that each event is played at the proper time.
- [[file:src/conversions.lisp][conversions.lisp]] - functions to convert between units (i.e. midinote to frequency, decibels to amplitude, etc.).
- [[file:src/scales.lisp][scales.lisp]] - musical pitch (scales/tuning) data and structs.
- [[file:src/readtable.lisp][readtable.lisp]] - defines a named-readtable for optional syntax sugar.

- [[file:src/tests.lisp][tests.lisp]] - test suite using [[https://github.com/fukamachi/prove][prove]].

- [[file:src/supercollider.lisp][supercollider.lisp]] - code to interface cl-patterns with the [[https://github.com/byulparan/cl-collider][cl-collider]] library.
- [[file:src/cl-collider-extensions.lisp][cl-collider-extensions.lisp]] - a few additions to the cl-collider library for ease of use and cl-pattern interfacing.
- [[file:src/sc-compatibility.lisp][sc-compatibility.lisp]] - patterns that are 100% compatible with SuperCollider's (unlike the ones in patterns.lisp which aren't guaranteed to be).

- [[file:src/incudine.lisp][incudine.lisp]] - code to interface cl-patterns with [[https://github.com/titola/incudine][Incudine]].

- [[file:src/midi.lisp][midi.lisp]] - code to interface cl-patterns with [[https://github.com/defaultxr/cl-alsaseq][cl-alsaseq]].
