#+TITLE: Other Libraries

This document is a list of other libraries that you may find useful in conjunction with cl-patterns, and libraries with similar goals.

* Common Lisp audio

** [[https://github.com/byulparan/cl-collider][cl-collider]]
The primary backend that cl-patterns was developed against, a Lisp interface to the SuperCollider sound server.

** [[http://incudine.sourceforge.net/][Incudine]]
Another supported backend for cl-patterns. Written from the ground up and designed to be used with Lisp.

** [[https://github.com/ormf/cm][Common Music]]
The original Lisp music library. This repository is a fork of the last version before the project switched over to using Scheme exclusively.

** [[https://github.com/zkat/cl-openal][cl-openal]]
Lisp bindings to the [[https://www.openal.org/][OpenAL]] audio API, a cross-platform 3D audio API appropriate for use with gaming applications and many other types of audio applications.

* Common Lisp audio-related

Extensions and convenience functionality useful when working with the systems above.

** [[https://github.com/defaultxr/bdef][bdef]]
Buffer definition; audio buffer abstraction for Lisp sound synthesis systems. Abstracts away sound loading, file conversion, metadata handling, etc, to make working with buffers in systems like cl-collider and Incudine easier.

** [[https://github.com/defaultxr/cl-renoise][cl-renoise]]
Functionality to interface with [[https://www.renoise.com/][Renoise]] from Common Lisp.

** [[https://github.com/MegaLoler/Music][Music]]
A framework for musical expression in Lisp with a focus on music theory. (Unrelated to Common Music)

* Common Lisp graphics

** [[https://common-lisp.net/project/mcclim/][McCLIM]]
A native Lisp graphical user interface library. Uses Lisp idioms and ideas for the development of user interaction modes. May be useful for visualization of pattern or other musical data, and interaction with the Lisp process.

** [[https://github.com/cbaggers/cepl][CEPL]]
"Code Evaluate Play Loop". A project that attempts to make programming graphics on the GPU feel native to Lisp.

** [[https://github.com/borodust/cl-bodge][cl-bodge]]
"Experimental bodacious game engine written in Common Lisp". A modular and extensible framework for developing games and game-like applications in Lisp.

** [[https://github.com/vydd/sketch][Sketch]]
Common Lisp environment for the creation of visual art, game prototyping, etc. Similar in operation to the [[https://processing.org/][Processing]] (Java) library.

** [[https://github.com/volkers/vgplot][vgplot]]
A Common Lisp interface to gnuplot, a command line-driven cross-platform graphing utility.

* Common Lisp extensions

** [[http://cl21.org/][cl21]]
"Common Lisp for the 21st century". Extends and enhances Common Lisp with improvements to the syntax and functionality. May be useful for livecoders since many of its changes make Lisp more consistent and succinct. However, it seems to have gone dormant...

** [[https://github.com/vseloved/rutils][rutils]]
"Radical Utilities for Common Lisp". Extends Common Lisp with many additional functions and syntactic sugar, but unlike CL21 it remains backwards compatible with standard Common Lisp.

** [[https://github.com/rongarret/ergolib][ergolib]]
"A library designed to make programming in Common Lisp easier".

* Non-CL

** [[https://supercollider.github.io/][SuperCollider]]
Audio engine, programming language and IDE. Includes the original patterns system that cl-patterns was based on, as well as scsynth, the primary backend cl-patterns is written for.

** [[https://tidalcycles.org/][TidalCycles]]
Pattern sequencing library written in Haskell. Also uses SuperCollider as a backend. It's the inspiration for the ~pcycles~ pattern included in cl-patterns.

** [[http://www.pawfal.org/fluxus/][Fluxus]]
Racket (Scheme-like)-based environment for the live coding of 3D graphics and games. Includes functionality for simple analysis of audio and functions to handle OSC messages.

** [[https://overtone.github.io/][Overtone]]
Audio live coding environment in Clojure using the SuperCollider server as a backend.
