#+TITLE: Patterns
#+DESCRIPTION: Index of cl-patterns pattern classes
#+OPTIONS: num:nil

* list patterns
Patterns that generate output based on an input list.
- ~pseq~ - Simply yields each element of its input list in order.
- ~pser~ - Like ~pseq~, but instead of yielding the whole list N times, yields a total of N outputs.
- ~prand~ - Yields a random element from its input list.
- ~pxrand~ - Yields a random element from its input list, never yielding the same output twice in a row.
- ~pwrand~ - Yields a random element from its input list, based on a list of weights for each element.
- ~pwxrand~ - Yields a random element from a weighted list, never yielding the same output twice in a row.
- ~pshuf~ - Shuffles the input list, then yields the elements of the shuffled list in order a specified number of times.
- ~pslide~ - "Slide" across successive sections of a list, advancing the start point of the sublists by a specified amount between each.
- ~pindex~ - Get a specified element from the source list by its index.
- ~place~ - Interlace values from sublists of the input list.
- ~ppatlace~ - Interlace values from patterns in the input list.
- ~pwalk~ - Walk across the input list by moving relative to the current position in it.

* Curve patterns
Patterns that generate numbers according to curve formulae.
- ~pseries~ - Each element is the previous element plus a number.
- ~pgeom~ - Each element is the previous element multiplied by a number.
# - ~penv~ - FIX

* Randomness patterns
Patterns that generate random numbers.
- ~pwhite~ - White noise pattern; random numbers evenly distributed within a range.
- ~pbrown~ - Brownian motion pattern; random numbers within a range, where each number is a maximum amount away from the previous output.
- ~pexprand~ - Exponentially-distributed random numbers.

* Math patterns
Patterns whose outputs are the results of math operations on other patterns.
- ~p+~, ~p-~, ~p*~, ~p/~ - Basic math patterns.
- ~pdiff~ - Get the difference between successive outputs of the source pattern.
- ~pdelta~ - Get the difference between successive outputs of the source pattern, wrapping negatives within a specified range.

* Repetition patterns
Patterns that repeat or skip outputs from a source pattern.
- ~pr~ - Repeats (or skips) each output from its source pattern a specified number of times.
- ~pn~ - Loops its source pattern a specified number of times.
- ~pstutter~ - Repeats or skips each output from its source pattern a specified number of times. DEPRECATED; use ~pr~ instead as its features are a superset of ~pstutter~'s.
- ~pdurstutter~ - Repeats each element from its source pattern a specified number of times, dividing that element (or the duration of it if the element is an event) by that number.
- ~pdrop~ - Drop the first or last N outputs from a source pattern.

* Filter patterns
Patterns that generate output by transforming a source pattern.
- ~pclump~ - Clump outputs of the source pattern together into lists of N elements.
- ~paclump~ - Automatically clump the source's outputs into lists whose length matches the longest list in the current ~*event*~.

* Constraint patterns
Patterns that limit the number of, or values of, outputs from a source pattern.
- ~pconst~ - Limits the sum of the source pattern not to exceed a specified value.
- ~pfin~ - Limits the number of outputs yielded by its source pattern.
- ~pfindur~ - Limits the total duration of the outputs from its source pattern.
- ~psync~ - Limits the total duration of the outputs from its source pattern, 

* Timing patterns
Patterns that yield information about timing, or alter the timing of a source pattern.
- ~pbeat~ - Get the current beat of the pattern relative to its start.
- ~ptime~ - Get the current elapsed time in seconds of the pattern relative to its start.
- ~prun~ - Pretend to "run" a pattern in the background, yielding what the output would be at the current moment.
- ~pts~ - Timestretch a pattern's total duration to a specified number of beats.

* Referring patterns
Patterns whose outputs are generated by referring to the outputs of other patterns.
- ~pk~ - Gets the value of a previously-defined key from the enclosing pbind.
- ~phistory~ - Gets previous outputs of its source pattern by their index relative to the current.
- ~pscratch~ - DJ-like scratching or scrubbing through the outputs of its source pattern.
- ~ps~ - Preserve the source pattern's pstream state across invocations.

* Function patterns
Patterns that generate output based on an input function.
- ~pfunc~ - Yield the result returned by its input function. Unlike ~pnary~, ~pfunc~ does not supply arguments to its function.
- ~pf~ - Syntax sugar for ~pfunc~ so you don't have to write ~(lambda () ...)~.
- ~pnary~ - N-ary function pattern for applying a function to each of its arguments' outputs.
- ~plazy~ - Lazily generate a pattern in place of this one by using the result of the input function.
- ~plazyn~ - Like ~plazy~ but only calls the input function a maximum of N times.
- ~pif~ - "If" expression. If the source pattern returns a true value, yield the next output from the "then" pattern; otherwise, yield the next output from the "else" pattern.

* Domain-specific language patterns
Patterns that allow you to write in a "pseudo-language" which may be more suited to specific tasks.
- ~ptracker~ - "Tracker-like" way to specify event patterns. Like ~pbind~ but with parameters as columns instead of rows.
- ~pcycles~ - TidalCycles-inspired syntax, dividing time up by the elements of a source list.

* UGen patterns
Patterns whose functionalities are based on UGens.
- ~psinosc~ - Tempo-synced ~sin-osc~ emulation.

* Music patterns
Patterns whose outputs are based on music-related formulae or data.
- ~pbjorklund~ - Euclidean rhythm generation via the Bjorklund algorithm.
- ~psplits~ - Parameters to play sections of buffers defined via "split points". Available in the [[https://github.com/defaultxr/bdef][bdef]] library.

* Meta patterns
Patterns that are used to define or debug others.
- ~pbind~ - Basic event-stream-defining pattern.
- ~pb~ - Syntax sugar effectively combining the functionality of ~pdef~ and ~pbind~ together.
- ~pmono~ - Like ~pbind~, but for monophony instead of polyphony.
- ~pdef~ - Pattern definition. Give a global name to a pattern, which allows it to be changed while it's playing.
- ~ptrace~ - Prints the outputs of its source pattern; useful for debugging.
- ~pchain~ - Chain patterns together by using the first source pattern's output as the input to the second, etc.
- ~parp~ - "Arpeggiate" patterns by using each output of one pattern as input to a full play-through of the other.
- ~ppar~ - Play patterns in parallel so that their outputs appear together in one pstream while preserving timing.
- ~psym~ - Define a sequence of patterns by name to play in succession and/or parallel.
- ~pmeta~ - Meta-control patterns by applying various transformations to them with a ~pbind~-like syntax.
